export const recentTransactions = [
  {
    id: 1,
    title: "McDonald's",
    category: "Food",
    amount: -450,
    date: "Today",
    icon: "🍔",
    color: "green",
  },
  {
    id: 2,
    title: "Uber",
    category: "Travel",
    amount: -320,
    date: "Yesterday",
    icon: "🚕",
    color: "blue",
  },
  {
    id: 3,
    title: "Salary",
    category: "Income",
    amount: 80000,
    date: "23 Jul",
    icon: "💰",
    color: "emerald",
  },
  {
    id: 4,
    title: "Electricity Bill",
    category: "Bills",
    amount: -1850,
    date: "22 Jul",
    icon: "💡",
    color: "violet",
  },
  {
    id: 5,
    title: "Amazon",
    category: "Shopping",
    amount: -2400,
    date: "20 Jul",
    icon: "🛒",
    color: "cyan",
  },
];